modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Tamaized/MelonGolem/issues"
license="All Rights Reserved"
[[mods]]
modId="melongolem"
version="${version}"
displayName="Melon Golem"
credits=""
authors="Tamaized"
description='''
Adds a Melon Golem
'''