modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Tamaized/MelonGolem/issues"
license="All Rights Reserved"
[[mods]]
modId="melongolem"
version="${version}"
displayName="Melon Golem"
credits=""
authors="Tamaized"
description='''
Adds a Melon Golem
'''

[[dependencies.melongolem]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.melongolem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
