modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Tamaized/MelonGolem/issues"
license="All Rights Reserved"
[[mods]]
modId="melongolem"
version="1"
displayName="Melon Golem"
credits=""
authors="Tamaized"
description='''
Adds a Melon Golem
'''